local frame = CreateFrame("Frame", nil, UIParent)
frame:SetSize(32, 32)
frame:SetFrameStrata("TOOLTIP")
local texture = frame:CreateTexture(nil, "OVERLAY")
texture:SetTexture("Interface\\Cooldown\\star4")
texture:SetAllPoints(frame)
texture:SetBlendMode("ADD")
texture:SetAlpha(0.5)

frame:SetScript("OnUpdate", function()
    local x, y = GetCursorPosition()
    local scale = UIParent:GetEffectiveScale()
    frame:SetPoint("CENTER", UIParent, "BOTTOMLEFT", x/scale, y/scale)
end)
