local frame = CreateFrame("Frame")
frame:RegisterEvent("ACHIEVEMENT_EARNED")
frame:RegisterEvent("PLAYER_LEVEL_UP")

frame:SetScript("OnEvent", function(self, event)
    print("|cFF00FF00MidnightScreenshots:|r Taking screenshot in 1 second...")
    C_Timer.After(1, function()
        Screenshot()
    end)
end)
