name: Upload Alpha Addons

on:
  push:
    paths:
      - 'Alpha/**'
  workflow_dispatch:

jobs:
  detect-alpha:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.set.outputs.addons }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect Alpha addons
        id: set
        run: |
          addons="[]"
          for dir in Alpha/*/; do
            if [ -f "$dir/.pkgmeta" ]; then
              addon_name=$(basename "$dir")
              addons=$(echo "$addons" | jq -c ". += [\"$addon_name\"]")
              echo "Found Alpha addon: $addon_name"
            fi
          done
          echo "addons=$addons" >> $GITHUB_OUTPUT

  release-alpha:
    needs: detect-alpha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ fromJson(needs.detect-alpha.outputs.addons) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy addon to root
        run: |
          cp -r Alpha/${{ matrix.addon }}/. .
          ls -la
          cat .pkgmeta
          cat *.toc

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@v2
        with:
          args: -g 11.0.5 -w 11.0.5 -p 1360857 -m .pkgmeta -n ${{ matrix.addon }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
