name: Upload Alpha Addons

on:
  push:
    paths:
      - 'Alpha/**'   # Solo se ejecuta si hay cambios en la carpeta Alpha
  workflow_dispatch:

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.detect.outputs.addons }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect Alpha addons
        id: detect
        run: |
          addons="[]"
          for dir in Alpha/*/; do
            if [ -f "$dir/.pkgmeta" ]; then
              addon_name=$(basename "$dir")
              addons=$(echo "$addons" | jq -c ". += [\"$addon_name\"]")
              echo "Found Alpha addon: $addon_name"
            fi
          done
          echo "addons=$addons" >> $GITHUB_OUTPUT

      - name: Upload Alpha addons
        uses: BigWigsMods/packager@v2
        with:
          args: ${{ join(fromJson(steps.detect.outputs.addons), " ") }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
