name: Upload Alpha Addons

on:
  push:
    paths:
      - 'Alpha/**'
  workflow_dispatch:

jobs:
  detect-alpha:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.detect.outputs.addons }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect Alpha addons
        id: detect
        run: |
          addons="[]"
          for dir in Alpha/*/; do
            if [ -f "$dir/.pkgmeta" ]; then
              addon_name=$(basename "$dir")
              addons=$(echo "$addons" | jq -c ". += [\"$addon_name\"]")
              echo "Found Alpha addon: $addon_name"
            fi
          done
          echo "addons=$addons" >> $GITHUB_OUTPUT

  release-alpha:
    needs: detect-alpha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ fromJson(needs.detect-alpha.outputs.addons) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy addon to root
        run: cp -r Alpha/${{ matrix.addon }}/. .

      - name: Run BigWigs Packager
        run: $GITHUB_ACTION_PATH/release.sh -g 11.0.5 -w 11.0.5 -p 1360857 -m .pkgmeta -n ${{ matrix.addon }} --build-type alpha
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
