name: Upload Addons to CurseForge

on:
  push:
    paths:
      - 'Alpha/**'
      - 'Beta/**'
  workflow_dispatch:

jobs:
  find-addons:
    runs-on: ubuntu-latest
    outputs:
      alpha-addons: ${{ steps.set-alpha.outputs.addons }}
      beta-addons: ${{ steps.set-beta.outputs.addons }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Detectar addons Alpha
      - name: Find Alpha addons
        id: set-alpha
        run: |
          addons="[]"
          for dir in Alpha/*/; do
            if [ -f "$dir/.pkgmeta" ]; then
              addon_name=$(basename "$dir")
              addons=$(echo "$addons" | jq -c ". += [\"$addon_name\"]")
              echo "Found Alpha addon: $addon_name"
            fi
          done
          echo "addons=$addons" >> $GITHUB_OUTPUT

      # Detectar addons Beta
      - name: Find Beta addons
        id: set-beta
        run: |
          addons="[]"
          for dir in Beta/*/; do
            if [ -f "$dir/.pkgmeta" ]; then
              addon_name=$(basename "$dir")
              addons=$(echo "$addons" | jq -c ". += [\"$addon_name\"]")
              echo "Found Beta addon: $addon_name"
            fi
          done
          echo "addons=$addons" >> $GITHUB_OUTPUT

  release-alpha:
    needs: find-addons
    if: needs.find-addons.outputs.alpha-addons != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package and upload Alpha addons
        run: |
          for addon in $(echo '${{ needs.find-addons.outputs.alpha-addons }}' | jq -r '.[]'); do
            echo "Packaging $addon as alpha..."
            cp -r Alpha/$addon/. .
            $GITHUB_ACTION_PATH/release.sh -g 11.0.5 -w 11.0.5 -p 1360857 -m .pkgmeta -n $addon --build-type alpha
          done
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

  release-beta:
    needs: find-addons
    if: needs.find-addons.outputs.beta-addons != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package and upload Beta addons
        run: |
          for addon in $(echo '${{ needs.find-addons.outputs.beta-addons }}' | jq -r '.[]'); do
            echo "Packaging $addon as beta..."
            cp -r Beta/$addon/. .
            $GITHUB_ACTION_PATH/release.sh -g 11.0.5 -w 11.0.5 -p 1360857 -m .pkgmeta -n $addon --build-type beta
          done
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
